# Generated by Django 3.2 on 2023-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('description', models.CharField(max_length=500, verbose_name='Описание организации')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес организации')),
                ('postcode', models.IntegerField(verbose_name='Почтовый индекс организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование мероприятия')),
                ('description', models.CharField(max_length=500, verbose_name='Описание мероприятия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение мероприятия')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('organization', models.ManyToManyField(to='events.Organization', verbose_name='Организующая мероприятие организация')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
    ]
